sudo: false
language: python
python:
  - '2.7'
cache:
  directories:
  - $HOME/gcloud/
env:
  global:
    - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client_secrets.json

before_install:
  - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then mkdir -p $HOME/gcloud && wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
    --directory-prefix=$HOME/gcloud && cd $HOME/gcloud && tar xzf google-cloud-sdk.tar.gz
    && printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh && cd $TRAVIS_BUILD_DIR;
    fi
  - gcloud -q components update
  - gcloud -q auth activate-service-account --key-file $TRAVIS_BUILD_DIR/client-secret.json
  - gcloud config set project guestbook3-184807 

install:
  - echo "Instalando"

before_script:
  - echo "Before script"

script:
  - echo "Script"

after_success:
  - gcloud -q app deploy app.yaml index.yaml
  # commenting this out since the dedicated ip addy was removed to avoid costs!
  # - TARGET_DB=$PROD_DB python main.py db upgrade
