deploy:
  provider: gae
  language: python
  python:
  - 2.7
  keyfile: client-secret2.json
  project: guestbook3-184807
  no_promote: true
  skip_cleanup: true
  default: true
before_install:
- openssl aes-256-cbc -K $encrypted_a2dae43ac7cf_key -iv $encrypted_a2dae43ac7cf_iv
  -in client-secret.json -out client-secret2.json -d
