sudo: false
language: python
python:
  - '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_a2dae43ac7cf_key -iv $encrypted_a2dae43ac7cf_iv
  -in client-secret.json -out client-secret.json -d
  - if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then mkdir -p $HOME/gcloud && wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
    --directory-prefix=$HOME/gcloud && cd $HOME/gcloud && tar xzf google-cloud-sdk.tar.gz
    && printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh && cd $TRAVIS_BUILD_DIR;
    fi
  - gcloud -q components update
  - if [ -a client_secrets.json ]; then gcloud -q auth activate-service-account --key-file
    client_secrets.json; fi
  - gcloud config set project guestbook3-184807

install:
  - pip install -t lib -r requirements.txt
  - pip install virtualenvwrapper
  - source virtualenvwrapper.sh
  - add2virtualenv ./lib
  - pip install coveralls

before_script:

script:

after_success:
  - gcloud -q preview app deploy app.yaml --version=1
